version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: game-game-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-game_game}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: game-game-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      PORT: "4000"
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-game_game}?schema=public
    depends_on:
      - postgres
    volumes:
      - api_uploads:/app/apps/api/uploads
    networks:
      - internal
      - proxy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://djam.tirskix.space/api
        NEXT_PUBLIC_SOCKET_URL: https://djam.tirskix.space
    container_name: game-game-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
    depends_on:
      - api
    networks:
      - internal
      - proxy

volumes:
  postgres_data:
  api_uploads:

networks:
  internal:
  proxy:
    external: true
